## numpy : creating an array

### from python structures like list, tuples etc

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))  #types tells the typoe of object passed to it . here the array type ie. ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


######  0D array  or Scalars : 
 

In [2]:
import numpy as np

arr = np.array(42)

print(arr)

42


###### 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [3]:
# Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


###### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

In [4]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


###### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.


In [5]:
###### Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


##### Number of Dimensions in array:
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [6]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [7]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


###### Array indexing :


You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [8]:
##Get the first element from the following array:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [9]:

#Get the second element from the following array.
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


###### Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.



In [10]:
#Access the second element from first row:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [11]:
#Access the element on the 2nd row, 5th column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])
print('5th element on 2nd row: ', arr[1][4])

5th element on 2nd row:  10
5th element on 2nd row:  10


In [23]:

import numpy as np
a = np.array([[12,13,15,17],[45,12,46,89],[34,0,90,80]])
print(a[:,1:3])   ## accessing elements of 1st and 2nd column of all rows 
print(a[0:2,2:4])  ## accessing elements of ist and 2nd row of columns 2nd and 3rd 

[[13 15]
 [12 46]
 [ 0 90]]
[[15 17]
 [46 89]]


###### Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [12]:
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0][1][1])

5


###### Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer


f - float

c - complex float

m - timedelta


M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [13]:
#Get the data type of an array object:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [14]:
#Get the data type of an array containing strings:

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [15]:
#Create an array with data type string:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [16]:
#Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [17]:
#Example A non integer string like 'a' can not be converted to integer (will raise an error):

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')


ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')   # ASTYPE CREATES THE COPY OF THE ARRAY

print(newarr)
print(newarr.dtype)
print(arr)

###### shape of the array: The shape of an array can be defined as the number of elements in each dimension.
syntax: numpy.shape(array_name)
Parameters: Array is passed as a Parameter.
Return: A tuple whose elements give the lengths of the corresponding array dimensions.

In [ ]:
import numpy as npy

a=np.array([1,2,3])
print(a.shape)
  
# creating a 2-d array
arr1 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
  
# creating a 2-d array
arr2 = np.array([[1, 3, 5, 7], [2, 4, 6, 8], 
                  [3, 6, 9, 12]])
arr3=np.array([[[1,2],[34,56]],[[23,67],[56,89]]])
arr4 = np.array([[1, 3, 5, 7]])
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)
print(arr4.shape)
arr5=np.array([[[1,2],[34,56]]])
print(arr5.shape)

In [ ]:
import numpy as npy
  
# creating an array of 6 dimension
# using ndim
arr = npy.array([2, 4, 6, 8, 10], ndmin=6)
  
# printing array
print(arr)
  
# verifying the value of last dimension
# as 5
print('shape of an array :', arr.shape)

##### Rank :- no of dimesnions or ndim

##### size of array : returns the no of elements  along the axis:

Syntax: numpy.size(arr, axis=None)
Parameters: 
arr: [array_like] Input data. 
axis: [int, optional] Axis(x,y,z) along which the elements(rows or columns) are counted. By default, give the total number of elements in a array
Returns: [int] Return the number of elements along a given axis. 

In [ ]:
# Python program explaining
# numpy.size() method
 
# importing numpy
import numpy as np
 
# Making a random array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
# By default, give the total number of elements.
print(np.size(arr))

In [ ]:

 
# importing numpy
import numpy as np
 
# Making a random array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
# count the number of elements along the axis.
# Here rows and columns are being treated
# as elements
 
#gives no. of rows along x-axis
print(np.size(arr, 0))
 
#gives no. of columns along y-axis
print(np.size(arr, 1))

In [ ]:
import numpy as np
a=np.array([1,2,3])
arr1 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
arr2 = np.array([[1, 3, 5, 7], [2, 4, 6, 8], [3, 6, 9, 12]])
arr3=np.array([[[1,2],[34,56]],[[23,67],[56,89]]])
arr4 = np.array([[1, 3, 5, 7]])
arr5=np.array([[[1,2],[34,56]]])
arr6=np.array([[[[[[12,3]]]]]])
print(np.size(a,0))
print(np.size(a))
print(np.size(arr1,0))
print(np.size(arr1,1))
print(np.size(arr2,0))
print(np.size(arr2,1))
print(np.size(arr3,0))
print(np.size(arr3,1))
print(np.size(arr3,2))
print(np.size(arr4,0))
print(np.size(arr4,1))
print(np.size(arr6,0))
print(np.size(arr6,5))
print(np.size(arr3))

###### copy and view 
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
## copy

import numpy as np

a = np.array([1, 2, 3, 4, 5])
a_c = a.copy()
print(a)
print(a_c)
a_c[2]=9
print("3rd value of copied array is changed: ",a_c)
print("original array remains same  :",a)

In [ ]:
## view 
import numpy as np

a = np.array([1, 2, 3, 4, 5])
a_c = a.view()
print(a)
print(a_c)
a_c[2]=9
print("3rd value of viewed array is changed: ",a_c)
print("original array becomes altered  same as new change  :",a)

###### reshape and resize
Both the numpy.reshape() and numpy.resize() methods are used to change the size of a NumPy array. The difference between them is that the reshape() does not changes the original array but only returns the changed array, whereas the resize() method returns nothing and directly changes the original array.

In [ ]:
import numpy as np 
    
# creating an array 
a = np.array([1, 2, 3, 4, 5, 6]) 
print("Orignal array:")
display(a)  
a1=a.reshape(2, 3)  
# using reshape()
print("Changed array")
display(a1) 
    
print("Original array:")
display(a)

In [ ]:
#resize
# importing the module
import numpy as np 
    
# creating an array 
a = np.array([1, 2, 3, 4, 5, 6]) 
print("Original array:")
display(a)  
a1=a.resize(2, 3) 
# using resize()
print("Changed array")
# this will print nothing as None is returned
display(a1) 
    
print("Original array:")
display(a)

In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


In [ ]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

##### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.  here elements would be different so no reshaping can be possible

###### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)


print(newarr)


In [ ]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, -1, 2)


print(newarr)

#####  We can not pass -1 to more than one dimension.

##### Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

nd array to 1d array :


1- reshape(-1)   
2- flatten()
3-ravel()

In [ ]:
#reshape and flatten 
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("original array is ",arr)

a1 = arr.reshape(-1)
print("1 D array :  ",a1)
print("original array remains same ",arr)
a2 = arr.flatten()
print("1 D array :  ",a2)
print("original array remains same  ",arr)


In [ ]:


import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("original array is ",arr)
a2 = arr.ravel()
print("1 D array :  ",a2)
print("original array changed  ",arr)

##### arange 

###### The arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half-opened i.e. [Start, Stop) 

Parameters : 

start : [optional] start of interval range. By default start = 0
stop  : end of interval range
step  : [optional] step size of interval. By default step size = 1,  
For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. 
dtype : type of output array
Return: 

Array of evenly spaced values.
Length of array being generated  = Ceil((Stop - Start) / Step) 

In [ ]:
import numpy as np
a=np.arange(1,11)
print(a)
a1=np.arange(1,11,2)
print(a1)
a2=np.arange(1.1,11.2,0.2)
print(a2)

##### Empty Array - Using numpy.empty
This is used to create an uninitialized array of specified shape and dtype.

The syntax to use this constructor is as follows:

numpy.empty(shape, dtype, order)  
Following is a description of parameters by this constructor:

shape: This parameter is used to indicate the desired shape of the specified array.

dtype: This parameter indicates the data type of the array items. The default value of this parameter is float.

order: The default order or value of this option is the c-style row-major order. This parameter can be set to F for FORTRAN-style (column-major order)

In [ ]:
import numpy as np 

# an array with 4 rows and 3 columns
x = np.empty([4,3], dtype = int) 
print (x)  # shows random values in array

In [ ]:
import numpy as np 

# an array with 2 elements
x = np.empty(4, dtype = int) 
print (x)  # shows ra

##### Zero Value Array - Using numpy.zeroes
This is used to return a new array of the specified size and each array item will be initialized with 0.

The syntax to use this constructor is as follows:

numpy.zeros(shape, dtype, order)  

In [ ]:
import numpy as np  

arr = np.zeros((3,3), dtype = int)  
print(arr)

##### One Value Array - Using numpy.ones
This is used to return a new array of the specified size and each array item will be initialized as 1.

The syntax to use this constructor is as follows:

numpy.ones(shape, dtype, order)  

In [ ]:
import numpy as np  

arr = np.ones((3,3), dtype = int)  
print(arr) 

In [ ]:
import numpy as np
distance=[2,3,4,5]
time=[4,6,7,8]
d=np.array(distance)
t=np.array(time)
s=d/t
print(s)

In [19]:
#TRACE : sum of diagnal elements
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
np.trace(a)

6

In [20]:
import numpy as np
a=np.array([1,2,3])
print(a)
print("dimension is  ",a.ndim)
print("shape is ",a.shape,"\n")
a=np.array([[1,2,3],[2,3,4]])
print(a)
print("dimension is ",a.ndim)
print("shape is ",a.shape,"\n")
a1=np.array([[[1,2,3],[2,3,4]]])
print(a1)
print("dimension is ",a1.ndim)
print("shape is  ",a1.shape,"\n")
a2=np.array([[[[1,2,3],[2,3,4]]]])
print(a2
     )
print("dimension is ",a2.ndim)
print("shape is  ",a2.shape)
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,4,7],[2,3,5],[7,8,10]]])
print(a3)
print("dimension is ",a3.ndim)
print("shape is ",a3.shape)

[1 2 3]
dimension is   1
shape is  (3,) 

[[1 2 3]
 [2 3 4]]
dimension is  2
shape is  (2, 3) 

[[[1 2 3]
  [2 3 4]]]
dimension is  3
shape is   (1, 2, 3) 

[[[[1 2 3]
   [2 3 4]]]]
dimension is  4
shape is   (1, 1, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 1  4  7]
  [ 2  3  5]
  [ 7  8 10]]]
dimension is  3
shape is  (2, 3, 3)


#### identity matrix : method eye()

In [25]:
import numpy as np
i=np.eye(3,k=0)    # here 3 is 3*3 k is used to write one based on its value if k=0 it writes one on diagnal element
print("identity matrix is :\n ",i,"\n and its shape is ",i.shape)

identity matrix is :
  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 and its shape is  (3, 3)


In [26]:
import numpy as np
i=np.eye(4,k=1)    # here k is used to write one based on its value if k=1 it writes one on the diagnal element on  first upper of the diagonal
print("identity matrix is :\n ",i,"\n and its shape is ",i.shape)

identity matrix is :
  [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]] 
 and its shape is  (4, 4)


In [27]:
import numpy as np
i=np.eye(4,k=2)    # here k is used to write one based on its value if k=2 it writes one on the diagnal element on second upper of the diagonal
print("identity matrix is :\n ",i,"\n and its shape is ",i.shape)

identity matrix is :
  [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 and its shape is  (4, 4)


In [28]:
import numpy as np
i=np.eye(4,k=-1)    # here k is used to write one based on its value if k=-1 it writes one on the diagnal element on first below of the diagonal
print("identity matrix is :\n ",i,"\n and its shape is ",i.shape)

identity matrix is :
  [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] 
 and its shape is  (4, 4)


In [29]:
import numpy as np
i=np.eye(4,k=-2)    # here k is used to write one based on its value if k=-2 it writes one on the diagnal element on second below of the diagonal
print("identity matrix is :\n ",i,"\n and its shape is ",i.shape)

identity matrix is :
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]] 
 and its shape is  (4, 4)


##### extarct diagonal elements and construct diagonal array : np.diag()

In [30]:
# fetching diagonal elements 
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("diagonal elements are : ",np.diag(a))   


[[1 2 3]
 [4 5 6]]
diagonal elements are :  [1 5]


In [31]:
# fetching diagonal elements of upper triangle 
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("diagonal elements are : ",np.diag(a,k=1))   


[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements are :  [2 6]


In [32]:
# fetching diagonal elements of lower  triangle 
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("diagonal elements are : ",np.diag(a,k=-1)) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements are :  [4 8]


In [33]:
# constructing diagonal array of  diagonal elements 
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
diag_ele=np.diag(a)
print("diagonal elements are : ",diag_ele)
print("diagonal array : \n",np.diag(diag_ele))  

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal elements are :  [1 5 9]
diagonal array : 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


In [ ]:
### diagflat : for creating diagonal array means the element is to be placed diagonally based on the value of k
import numpy as np
a1=np.diagflat([1,2,3],k=0)
print(a1)
a2=np.diagflat([1,2,3,4],k=-1)
print("\n ",a2)


#### tri , triu and tril 

In [34]:
'''numpy.tri(R, C = None, k = 0, dtype = ‘float’) : Creates an array with 1’s at and below the given diagonal(about k) \
and 0’s elsewhere.
Parameters :

R     : Number of rows
C     : [optional] Number of columns; By default R = C
k     : [int, optional, 0 by default]
               Diagonal we require; k>0 means diagonal above main diagonal or vice versa.
dtype : [optional, float(byDefault)] Data type of returned array.  
'''
import numpy as np
a=np.tri(3,3,dtype=int)  # k=0
print(a)
a=np.tri(3,3,-1,dtype=int)  #k=-1
print("\n",a)
a=np.tri(3,3,-2,dtype=int)  #k=-2
print("\n",a)
a=np.tri(3,3,1,dtype=int)  #k=1
print("\n",a)
a=np.tri(3,3,2,dtype=int)  #k=2
print("\n",a)

[[1 0 0]
 [1 1 0]
 [1 1 1]]

 [[0 0 0]
 [1 0 0]
 [1 1 0]]

 [[0 0 0]
 [0 0 0]
 [1 0 0]]

 [[1 1 0]
 [1 1 1]
 [1 1 1]]

 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# triu(input array,value of k(default=0))  :   Returns copy of array with upper part of the triangle w.r.t k
import numpy as np
a=[[1, 21, 30], 
    [63 ,434, 3], 
    [54, 54, 56]]
u_array=np.triu(a,k=0 ) 
print(u_array)
u_array1=np.triu(a,k=1) 
print("\n",u_array1)
u_array2=np.triu(a,k=2) 
print("\n",u_array2)
u_array3=np.triu(a,k=-1) 
print("\n",u_array3)


In [35]:
'''numpy.tril(a, k=0) : Returns copy of array with lower part of the triangle w.r.t k
a : input array
k : [int, optional, 0 by default]
          Diagonal we require; k>0 means diagonal above main diagonal or vice versa.'''
import numpy as np
a=[[1, 21, 30], 
    [63 ,434, 3], 
    [54, 54, 56]]
a1=np.tril(a,k=0 )
print(a1)
a1=np.tril(a,k=-1 )
print("\n",a1)
a1=np.tril(a,k=-2 )
print("\n",a1)
a1=np.tril(a,k=1 )
print("\n",a1)
a1=np.tril(a,k=2 )
print("\n",a1)

[[  1   0   0]
 [ 63 434   0]
 [ 54  54  56]]

 [[ 0  0  0]
 [63  0  0]
 [54 54  0]]

 [[ 0  0  0]
 [ 0  0  0]
 [54  0  0]]

 [[  1  21   0]
 [ 63 434   3]
 [ 54  54  56]]

 [[  1  21  30]
 [ 63 434   3]
 [ 54  54  56]]
